export type PermissionSet = {
  name: string;
  description: string;
  type: "System" | "Custom";
  permissions: number;
  roles: string[];
  lastModified: string;
  status: "Active" | "Needs review";
};

export const permissionSets: PermissionSet[] = [
  {
    name: "Users",
    description: "Manage user accounts, roles, and invitations.",
    type: "System",
    permissions: 12,
    roles: ["Owner", "Admin", "Manager", "Support", "Marketing", "Project Lead"],
    lastModified: "Apr 12, 2025",
    status: "Needs review",
  },
  {
    name: "Settings",
    description: "Configure workspace and organization settings.",
    type: "System",
    permissions: 8,
    roles: ["Owner", "Admin", "Developer", "Project Lead"],
    lastModified: "Apr 15, 2025",
    status: "Needs review",
  },
  {
    name: "Billing",
    description: "Access invoices, payments, and subscription plans.",
    type: "System",
    permissions: 6,
    roles: ["Owner", "Admin", "Billing", "Finance Viewer"],
    lastModified: "Apr 20, 2025",
    status: "Active",
  },
  {
    name: "Reports",
    description: "View and generate analytics and business reports.",
    type: "System",
    permissions: 10,
    roles: [
      "Owner",
      "Admin",
      "Manager",
      "Support",
      "Analyst",
      "Guest",
      "Billing",
      "Marketing",
      "Finance Viewer",
      "Project Lead",
    ],
    lastModified: "May 1, 2025",
    status: "Active",
  },
  {
    name: "Integrations",
    description: "Manage third-party integrations and webhooks.",
    type: "System",
    permissions: 5,
    roles: ["Owner", "Admin", "Service"],
    lastModified: "Apr 22, 2025",
    status: "Active",
  },
  {
    name: "Audit Logs",
    description: "View activity and audit trail across the workspace.",
    type: "System",
    permissions: 3,
    roles: ["Owner"],
    lastModified: "Apr 12, 2025",
    status: "Active",
  },
  {
    name: "Tickets",
    description: "Create and resolve support tickets.",
    type: "System",
    permissions: 7,
    roles: ["Support"],
    lastModified: "May 1, 2025",
    status: "Active",
  },
  {
    name: "Analytics",
    description: "Access dashboards and data analytics features.",
    type: "System",
    permissions: 9,
    roles: ["Analyst", "Marketing"],
    lastModified: "May 5, 2025",
    status: "Active",
  },
  {
    name: "Exports",
    description: "Export data to CSV, Excel, and other formats.",
    type: "System",
    permissions: 4,
    roles: ["Analyst", "Marketing", "Finance Viewer"],
    lastModified: "May 2, 2025",
    status: "Active",
  },
  {
    name: "Projects",
    description: "Manage projects, milestones, and assignments.",
    type: "Custom",
    permissions: 8,
    roles: ["Manager", "Project Lead"],
    lastModified: "Apr 30, 2025",
    status: "Active",
  },
  {
    name: "Tasks",
    description: "Create, assign, and track individual tasks.",
    type: "Custom",
    permissions: 6,
    roles: ["Manager", "Project Lead"],
    lastModified: "Apr 30, 2025",
    status: "Active",
  },
  {
    name: "API Keys",
    description: "Generate and manage API keys for external access.",
    type: "System",
    permissions: 4,
    roles: ["Service", "Developer"],
    lastModified: "Apr 22, 2025",
    status: "Active",
  },
  {
    name: "Repos",
    description: "Access code repositories and version control.",
    type: "Custom",
    permissions: 5,
    roles: ["Developer"],
    lastModified: "May 3, 2025",
    status: "Active",
  },
  {
    name: "Deployments",
    description: "Trigger and monitor deployment pipelines.",
    type: "Custom",
    permissions: 6,
    roles: ["Developer"],
    lastModified: "May 3, 2025",
    status: "Active",
  },
  {
    name: "Webhooks",
    description: "Configure webhook endpoints and event subscriptions.",
    type: "System",
    permissions: 3,
    roles: ["Service", "Developer"],
    lastModified: "Apr 22, 2025",
    status: "Active",
  },
  {
    name: "Logs",
    description: "View application and system logs.",
    type: "System",
    permissions: 4,
    roles: ["Service", "Developer"],
    lastModified: "Apr 22, 2025",
    status: "Active",
  },
  {
    name: "Invoices",
    description: "Create, send, and track invoices.",
    type: "Custom",
    permissions: 7,
    roles: ["Billing", "Finance Viewer"],
    lastModified: "Apr 28, 2025",
    status: "Active",
  },
  {
    name: "Payments",
    description: "Process and reconcile incoming payments.",
    type: "Custom",
    permissions: 5,
    roles: ["Billing"],
    lastModified: "Apr 28, 2025",
    status: "Active",
  },
  {
    name: "Campaigns",
    description: "Create and manage marketing campaigns.",
    type: "Custom",
    permissions: 8,
    roles: ["Marketing"],
    lastModified: "May 2, 2025",
    status: "Active",
  },
  {
    name: "Dashboards",
    description: "View and customize analytics dashboards.",
    type: "System",
    permissions: 5,
    roles: ["Analyst", "Guest", "Finance Viewer"],
    lastModified: "May 6, 2025",
    status: "Active",
  },
  {
    name: "Knowledge Base",
    description: "Manage internal documentation and help articles.",
    type: "Custom",
    permissions: 6,
    roles: ["Support"],
    lastModified: "May 1, 2025",
    status: "Active",
  },
];
